/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2018-04-16 13:51:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Supervisor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <link href=\"css/layout1.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header><center>Towson University</center></header>\n");
      out.write("<form name=\"inputdetails\" action=\"store\" method=\"post\" id=\"form1\">\n");
      out.write("<div><b>Details</b> \n");
      out.write("\n");
      out.write("<button id =\"b2\" type=\"submit\" formaction=\"login.html\">logout</button>\n");
      out.write("<button id =\"b1\" type=\"submit\" formaction=\"Supervisorshow.jsp\">View Details</button> \n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<fieldset>\n");
      out.write("<center>\n");
      out.write("<b>First Name:</b> <input type=text style=\"width: 200px;\" name=\"fname\" placeholder=\"firstname\"><br><br>\n");
      out.write("<b>Last Name:</b> <input type=text style=\"width: 200px;\" name=\"lname1\" placeholder=\"lastname\"><br><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("<b>Email:</b><input type=text style=\"width: 300px; align:center;\" name=\"email\" placeholder=\"Email \"><br><br>\n");
      out.write("<b>Items:</b></br>\n");
      out.write("<textarea rows=\"5\" cols=\"60\"  maxlength=\"260\" name=\"items\" placeholder=\"Please enter Items List\">\n");
      out.write("</textarea> <br><br>\n");
      out.write("Supplied date<input type=text name=\"sdate\" placeholder=\"yyyy/mm/dd\" ><br><br>\n");
      out.write("Return date<input type=text name=\"rdate\" placeholder=\"yyyy/mm/dd\" ><br><br>\n");
      out.write("<input type=submit value=submit> <br><br><br><br><br>\n");
      out.write("</center></fieldset>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("<footer> &copy 2018 - Towson University</footer>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
