/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2018-04-16 12:49:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.lang.*;
import java.util.*;

public final class Supervisorshow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <link href=\"css/layout1.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<header><center>Towson university</center></header>\n");
      out.write("<form name=\"inputdetails\" action=\"\" method=\"post\" id=\"form1\">\n");
      out.write("<div ><b>Details</b> \n");
      out.write("\n");
      out.write("<button id =\"b2\" type=\"submit\" formaction=\"login.html\">logout</button>\n");
      out.write("<button id =\"b1\" type=\"submit\" formaction=\"Supervisor.jsp\">Go back</button> \n");
      out.write("</div>\n");
      out.write("<fieldset><center>\n");
      out.write("\n");
      out.write("<!-- <b>CustId:</b> <input type=text style=\"width: 200px;\" name=\"custid \" placeholder=\"customer ID\"><br><br> -->\n");
      out.write("<!-- <b>CustName:</b><input type=text style=\"width: 300px; align:center;\" name=\"custname\" placeholder=\"customer name \"><br><br> -->\n");
      out.write("<!-- <b>Items:<b/><br/> -->\n");
      out.write("<!-- <textarea rows=\"5\" cols=\"60\"  maxlength=\"260\" name=\"items\" placeholder=\"Please enter Items List\"> -->\n");
      out.write("<!-- </textarea> <br><br> -->\n");
      out.write("<!-- <input type=checkbox name=\"return\" value=1>return<br><br> -->\n");
      out.write("<!-- Supplied date<input type=text name=\"sdate\" placeholder=\"Supply Date\" ><br><br> -->\n");
      out.write("<!-- Returned date<input type=text name=\"rdate\" placeholder=\"Return Date\" ><br><br> -->\n");
      out.write("<!-- <input type=submit value=submit> <br><br><br><br><br> -->\n");
      out.write("\n");
      out.write("</center></fieldset>\n");
      out.write("</form>\n");

Connection con=null;
try {
	 
	 
//	 Connection con1=db.getconnection();
	 
	 
	 try{
		 Class.forName("com.mysql.jdbc.Driver");
		con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/supervision","root","root");
		System.out.println("Connection Object"+con+"HERERERERERERERERER");

}
catch(Exception e){
e.printStackTrace();	
}
	 
	
	 PreparedStatement ps=con.prepareStatement("select * from supervision.items");
	 ResultSet rs=ps.executeQuery();
	 System.out.println(rs.getRow()+"HERERERERRRR");
	 rs.beforeFirst();
	 //System.out.println(rs.isBeforeFirst());
	 System.out.println(rs.getRow()+"HERERABCDRR");
		
	

      out.write("\n");
      out.write("\n");
      out.write("\"<TABLE  BORDER=\"3\" colspan=\"2\"  WIDTH=\"100%\"   CELLPADDING=\"8\" CELLSPACING=\"5\"> \n");
      out.write("\t\t   <TR>\n");
      out.write("\t\t   <TD><b>FirstName</b></TD> \n");
      out.write("\t\t    <TD><b>Last Name</b></TD> \n");
      out.write("\t\t    <TD><b>Email Id</b></TD> \n");
      out.write("\t\t   <TD><b>Items</b></TD> \n");
      out.write("\t\t    <TD><b>SupplyDate</b></TD> \n");
      out.write("\t\t   <TD><b>Return Date</b></TD>\n");
      out.write("\t\t   <TD><b>is Returned</b> </TD> \n");
      out.write("\t\t   </TR>\n");
      out.write("\t\t   \n");
      out.write("\t");
  int i=1;
	 while(rs.next()){ 
      out.write("\n");
      out.write("\t\t <TR>\n");
      out.write("\t\t   <TD>");
out.println(rs.getString(1)); 
      out.write("</TD> \n");
      out.write("\t\t   <TD>");
out.println(rs.getString(2)); 
      out.write("</TD> \n");
      out.write("\t\t   <TD>");
out.println(rs.getString(3));
      out.write("</TD> \n");
      out.write("\t\t    <TD>");
out.println(rs.getString(4)); 
      out.write("</TD> \n");
      out.write("\t\t   <TD>");
out.println(rs.getString(6)); 
      out.write("</TD>\n");
      out.write("\t\t   <TD>");
out.println(rs.getString(7));
      out.write("</TD> \n");
      out.write("\t\t   <TD>");
 out.println(rs.getString(5));
      out.write("</TD>\n");
      out.write("\t\t   </TR>\n");
      out.write("\t\t ");
 //System.out.println(rs.getString(i)+"      "+rs.getString(2)+"                  "+rs.getString(3)+"                  "+rs.getString(4)+"                  "+rs.getString(5)+"      "+rs.getString(6)+"      "+rs.getString(7));
	
      out.write("\n");
      out.write("\t\t   ");
 
	 }
	 }
	 catch(Exception e) {
		 e.printStackTrace();
	 }	   
con.close();

      out.write("   \n");
      out.write("\t\t   \n");
      out.write("\t\t   </TABLE>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<footer> &copy 2018 - Towson University</footer>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
